apiVersion: v1
kind: Service
metadata:
  name: seriescatalog-api
  namespace: seriescatalog
  labels:
    app.kubernetes.io/name: seriescatalog-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seriescatalog-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
