apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seriescatalog
resources:
  - namespace.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-keys-pvc.yaml
  - frontend-service.yaml
  - ingress.yaml
