apiVersion: v1
kind: Secret
metadata:
  name: seriescatalog-mongo
  namespace: seriescatalog
type: Opaque
stringData:
  MONGO_CONNECTION_STRING: "mongodb+srv://replace-with-user:replace-with-password@replace-cluster.mongodb.net/"
  MONGO_DATABASE_NAME: "replace-with-database-name"
