apiVersion: v1
kind: Secret
metadata:
  name: seriescatalog-mongo
  namespace: seriescatalog
type: Opaque
stringData:
  MONGO_CONNECTION_STRING: "mongodb+srv://w0519367_db_user:fsWjTsZevC1wif99@cluster0.25flnyu.mongodb.net/"
  MONGO_DATABASE_NAME: "harlan_coben"
