services:
  api:
    build:
      context: ../../
      dockerfile: deploy/docker/api/Dockerfile
    container_name: series-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__ConnectionString: ${MONGO_CONNECTION_STRING}
      Mongo__DatabaseName: ${MONGO_DATABASE_NAME}

  frontend:
    build:
      context: ../../
      dockerfile: deploy/docker/frontend/Dockerfile
    container_name: series-frontend
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Api__BaseUrl: http://api:8080
    depends_on:
      - api
