apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../oci

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: seriescatalog-api
    path: api-replicas-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: seriescatalog-frontend
    path: frontend-replicas-patch.yaml
