- op: replace
  path: /spec/ingressClassName
  value: nginx
- op: remove
  path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.entrypoints
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1affinity
  value: cookie
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1session-cookie-name
  value: seriescatalog-route
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1session-cookie-path
  value: /
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1session-cookie-max-age
  value: "86400"
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1session-cookie-expires
  value: "86400"
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-read-timeout
  value: "3600"
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-send-timeout
  value: "3600"
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1proxy-connect-timeout
  value: "60"
