apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/darrenmartell/seriescatalog-api
    newName: docker-api
    newTag: latest
  - name: ghcr.io/darrenmartell/seriescatalog-frontend
    newName: docker-frontend
    newTag: latest

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: seriescatalog-ingress
    path: ingress-json-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: seriescatalog-api
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: seriescatalog-frontend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
