apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: ghcr.io/darrenmartell/seriescatalog-api
    newName: docker-api
    newTag: latest
  - name: ghcr.io/darrenmartell/seriescatalog-frontend
    newName: docker-frontend
    newTag: latest

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: seriescatalog-ingress
    path: ingress-json-patch.yaml
