services:
  oci-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: seriescatalog/oci-cli:latest
    container_name: oci-cli
    restart: unless-stopped
    volumes:
      - ${USERPROFILE:-.}/.oci:/oracle/.oci
      - ${USERPROFILE:-.}/.kube:/oracle/.kube
      - ../../..:/workspace
    working_dir: /workspace
    environment:
      - OCI_CLI_CONFIG_FILE=/oracle/.oci/config
      - KUBECONFIG=/oracle/.kube/config
